# -*- coding: utf-8 -*-
"""hello_world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YLzgZWgK-5dDryRLYhJIiHMHR5i0Z_IE
"""

print("Hello World")
print("Belajar AI")
